### ISSUE TITLE
隐私文件

### ISSUE THREAD

**Issue by Deycoesr** [ljl2107/imageshack#1]
兄弟你这个[考试.jpg](https://github.com/ljl2107/imageshack/blob/main/%E8%80%83%E8%AF%95.jpg)有点暴露隐私信息了呀

**Comment by ljl2107** [comment]
啊啊啊，多谢多谢提醒，不然我一直都认识不到这个隐患ε=ε=ε=(ﾟ◇ﾟﾉ)ﾉ
已经修正，未来多多注意。再次感谢੭ ᐕ)੭*⁾⁾
